---
output: md_document
---
```{r include = FALSE}
source("../tools/chunk-options.R")
```

# Data types

<!--sec data-title="Learning Objectives" data-id="obj" data-show=true data-collapse=false ces-->

* to fill in later

<!--endsec-->

<br>

---

**Table of Contents**

<!-- toc -->

<br>

---

## Introduction


So now we know about variables, what sort of information can we store in them? In spoken language we have nouns, verbs, adverbs, etc. In programming we can use numbers, logical values and character strings. 
Numbers can be whole numbers (integers) such as 1, 2, 3, they can be doubles with decimal point values 1.25 or they can be complex numbers with imaginary components 3 + 2i.
Logical values, also known as Boolean values, can be either TRUE or FALSE. This is useful when comparing data
Character strings are made up of letters and special characters and are generally surrounded by quotation marks. Here we have research and platforms as two separate character strings
On each table you have red, yellow and blue pieces of paper. On one side it tells you what data type it is. I want you to write appropriate examples on the other side of the paper. One example per piece of paper. So the red paper is numeric, you could put the number 2 on the back. The yellow paper is logical, so you can put either true or false on each page and the blue paper is for character strings, so you can write whatever you want on these and surround it with quotation marks. You have 5 minutes to do this.

