---
output: md_document
---
```{r include = FALSE}
source("../tools/chunk-options.R")
```

# Data types

<!--sec data-title="Learning Objectives" data-id="obj" data-show=true data-collapse=false ces-->

* to fill in later

<!--endsec-->

<br>

---

**Table of Contents**

<!-- toc -->

<br>

---

## Introduction

The first thing to realise about programming, is that if you want the computer to remember something, you need to give it a name. You could just use your computer as a calculator, and type 1 + 1, which will return 2, but if you didn’t give it a name, then as soon as the computer has calculated the answer for you, it has already forgotten about it. It would be like talking to someone with amnesia, or for those of you with a disney/pixar interest, like talking to Dory. You would say ‘What is 1+1?’, the computer responds with ‘2’, then you would say what was the result of the last sum I gave you and the computer would say ‘what sum’?
So let’s have a go at naming things. Can someone give me a name for this abstract object? How about naming this baby? By giving them a name, you have made them into variables, which we can now remember. In the same way, if you name things when programming, your computer can store them in memory and access them later by that name. 
The contents of the variable can change, but the name stays the same. Much like *insert baby name here* will look different as she grows up, but (unless she goes through legal channels to change it) her name will always be ...
It’s important to note that if you start using a name that you haven’t introduced the computer to yet, the computer will get confused and return an error. Much like if I start talking to you about flickledutts. “Flickledutts is awesome, don’t you think so?” You’re probably now wondering what I’m talking about. What do you think flickledutts is? *wait* But if I tell you that flickledutts is a new board game, confusion gone. 
So we create variables that the computer can store in its memory by giving them names and we need to define variables before we refer to them in our code
Here are a couple of example in R of creating variables. The name of the variable is on the left and the value of the variable on the right, with this left hand arrow meaning assign. So this first line says create a variable called baby and assign it the value Meredith. And the second line says create a variable called sculpture and assign it the value 10


